server:
  port: 8088
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dlyk?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123.
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30
      connection-timeout: 5000
      idle-timeout: 0
      max-lifetime: 1800000

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


mybatis:
  mapper-locations: classpath:com.powernode.mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 定义定时任务的调度时间
project:
  task:
    cron: '* */5 * * * *'
    delay: 180000